"""initial schema

Revision ID: 93e6081a0562
Revises: 
Create Date: 2026-02-22 10:40:19.493444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e6081a0562'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campuses'))
    )
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('execution_mode', sa.Enum('MANUAL', 'ASSISTED', 'AUTO', name='executionmode'), nullable=False),
    sa.Column('payment_mode', sa.Enum('COUNTER', 'PREPAID', 'BOTH', name='paymentmode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_shops_campus_id_campuses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'SHOP_ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_users_campus_id_campuses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('print_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('A4', 'A3', name='papersize'), nullable=False),
    sa.Column('color_mode', sa.Enum('BW', 'COLOR', name='colormode'), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('execution_mode_snapshot', sa.Enum('MANUAL', 'ASSISTED', 'AUTO', name='executionmode'), nullable=False),
    sa.Column('payment_mode_snapshot', sa.Enum('COUNTER', 'PREPAID', 'BOTH', name='paymentmode'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'READY_TO_PRINT', 'PRINTING', 'PRINTED', 'COLLECTED', 'CANCELLED', name='printstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_print_jobs_campus_id_campuses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_print_jobs_shop_id_shops'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_print_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_jobs'))
    )
    op.create_index(op.f('ix_print_jobs_campus_id'), 'print_jobs', ['campus_id'], unique=False)
    op.create_index(op.f('ix_print_jobs_shop_id'), 'print_jobs', ['shop_id'], unique=False)
    op.create_index('ix_print_jobs_shop_status', 'print_jobs', ['shop_id', 'status'], unique=False)
    op.create_index(op.f('ix_print_jobs_status'), 'print_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_print_jobs_user_id'), 'print_jobs', ['user_id'], unique=False)
    op.create_table('shop_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.Enum('A4', 'A3', name='papersize'), nullable=False),
    sa.Column('color_mode', sa.Enum('BW', 'COLOR', name='colormode'), nullable=False),
    sa.Column('normal_rate', sa.Float(), nullable=False),
    sa.Column('bulk_rate', sa.Float(), nullable=False),
    sa.Column('bulk_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_pricing_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_pricing'))
    )
    op.create_index(op.f('ix_shop_pricing_shop_id'), 'shop_pricing', ['shop_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gateway_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['print_jobs.id'], name=op.f('fk_payments_job_id_print_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('job_id', name=op.f('uq_payments_job_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_index(op.f('ix_shop_pricing_shop_id'), table_name='shop_pricing')
    op.drop_table('shop_pricing')
    op.drop_index(op.f('ix_print_jobs_user_id'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_status'), table_name='print_jobs')
    op.drop_index('ix_print_jobs_shop_status', table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_shop_id'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_campus_id'), table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shops')
    op.drop_table('campuses')
    # ### end Alembic commands ###
